### ISSUE TITLE
Question concerning the hardware.

### ISSUE THREAD

**Issue by OrrinFox** [adafruit/Adafruit-USB-Serial-RGB-Character-Backpack#1]
I made some small improvements to your firmware here and would like to flash it to my lcd backpack ( Teensy 1.0 by the looks of it. ) I was wondering if any of you knew how to reset it into HalfKay ( To flash the new firmware ). Any help would be greatly appreciated. Thank you!

**Comment by OrrinFox** [comment]
P.S. at first it seemed as simple as shorting the "reset" io port on the board with a ground. It does "reset" it but does not seem to get it into the flash program.

**Comment by OrrinFox** [comment]
You may mark this as solved, should let the others know that this uses the avr109 compatible lufa bootloader!  I had to find out using some bus hacking!

**Comment by ladyada** [comment]
Just saw this now, thanks for the reminder,  its been added here!
https://learn.adafruit.com/usb-plus-serial-backpack/downloads
:)

**Comment by OrrinFox** [comment]
I do have one more question to ask later, Ill open a ticket when I get home
unless I could ask it here.
