### ISSUE TITLE
reprogram AT90USB162 

### ISSUE THREAD

**Issue by luisrx7** [adafruit/Adafruit-USB-Serial-RGB-Character-Backpack#7]
I need to reprogram the backpack can you point me how to do it? thanks

**Comment by transmogrifox** [comment]
Maybe a bit late, but look at these:
https://github.com/CanyonCasa/BackpackPlus
https://github.com/transmogrifox/Adafruit_USB_Backpack_Plus

CanyonCasa repo is a good starting point and includes all the extra's you need to recover to the original if you want to restore your stock USB backpack (as received from Adafruit).

In CanyonCasa's repo and mine the method is the same (I shamelessly forked CanyonCasa for a starting point):
Clone the repository
Enter the "build" directory.
Edit the makefile changing the PORT to whatever COM port your backpack shows up on.
Issue "make"
Get "make burn" ready on your terminal
Short RESET pin to GND and as soon as you see the screen flash red, hit "enter" on "make burn" command.

It will look like your unit does not work , but not to fear you only need to erase the EEPROM.  You can use the commands for writing EEPROM in a script to zero everything, or you can first flash the EEPROM eraser program (CanyonCasa supplied the source but not the .hex, but I built the .hex file in my repo so you don't have to re-compile it).  You can use avr-dude and CanyonCasa's instructions to flash the erase EEPROM image to your device.  Then you can do the steps above to write your final image.

This all assumes you have already installed the gcc cross-compiler for AVR, gnu make utilities and avr-dude.

A final note is if you make a bad image and flash it you can overwrite the bootloader and brick your unit.  To recover that you need to have an AVR debugger tool to connect to other pins on the board.  If you aren't doing a lot of AVR development or doing several of these then a new USB backpack is cheaper as a one-time purchase.  Of course if you brick your second unit then that's a sign you're doing enough development to warrant buying an AVR debugger/programmer.

**Comment by sneakin** [comment]
Not late at all. I finally figured out I only needed a new USB cable for my LCD and got the bug to look at firmware hacks again. Exactly what I needed way back when. This really should be bumped up to the official docs by now.
